export const DROP_FROM_LAID_TO_LAID = 'DROP_FROM_LAID_TO_LAID';
export const DROP_FROM_LAID_TO_SLOT = 'DROP_FROM_LAID_TO_SLOT';
export const DROP_FROM_SLOT_TO_SLOT = 'DROP_FROM_SLOT_TO_SLOT';
export const DROP_FROM_SLOT_TO_LAID = 'DROP_FROM_SLOT_TO_LAID';
export const DROP_FROM_SLOT_TO_HOME = 'DROP_FROM_SLOT_TO_HOME';
export const DROP_FROM_LAID_TO_HOME = 'DROP_FROM_LAID_TO_HOME';
export const HOME_SLOT_START_INDEX = 4;

export const DRAGGABLE_CARD_Z_INDEX = 500;
export const KING_RATE = 13;
export const ACE_RATE = 1;